default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: feedspin_development

test:
  <<: *default
  database: feedspin_test

production:
  <<: *default
  database: feedspin_production
  username: feedspin
  password: <%= ENV['FEEDSPIN_DATABASE_PASSWORD'] %>
